version: '3.8'

services:
  nextjs:
    build:
      context: .  # Build the Dockerfile in the current directory
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Map port 3000 on the host to port 3000 in the container
    volumes:
      - .:/app  # Mount the current directory to /app in the container
      - /app/node_modules  # Avoid overwriting node_modules in the container
    environment:
      - NODE_ENV=development
    command: npm run dev